import { Router } from "express";
import { AutorizacionGateway } from "../config/ws.adapter";
import { buildAuthMiddleware } from "../infrastructure/factories/auth.middleware.factory";
import { CategoriaProductoRoutes } from "./categoria-productos/routes";
import { ProveedoresRoutes } from "./proveedores/routes";
import { ClientesRoutes } from "./clientes/routes";
import { RepartidorRoutes } from "./repartidor/routes";
import { RolesRoutes } from "./roles/routes";
import { PermisosRoutes } from "./permisos/routes";
import { EmpresasRoutes } from "./empresa/routes";
import { PagosRoutes } from "./pagos/routes";
import { ProductosRoutes } from "./producto/routes";
import { AuthRoutes } from "./auth/routes";
import { DeliveryRoutes } from "./delivery/routes";
import { SesionesRoutes } from "./sesiones/routes";
import { VentasRoutes } from "./ventas/routes";
import { VentaDeliveryRoutes } from "./ventaDelivery/routes";
import { VentaProductoRoutes } from "./ventaProductos/routes";
import { VentaPagosRoutes } from "./venta-pagos/routes";
import { GastosRoutes } from "./gastos/routes";
import { PagoGastosRoutes } from "./pagoGastos/routes";
import { ComprasRoutes } from "./compras/routes";
import { ComprasProductosRoutes } from "./comprasProductos/routes";
import { MovimientosInventarioRoutes } from "./movimientosInventario/routes";
import { MovimientosComprasRoutes } from "./movimientosCompras/routes";
import { MovimientosVentasRoutes } from "./movimientosVentas/routes";
import { CuentasPorPagarRoutes } from "./cuentasPorPagar/routes";
import { PagoCuentasPorPagarRoutes } from "./pagoCuentasPorPagar/routes";
import { CuentasPorCobrarRoutes } from "./cuentasPorCobrar/routes";
import { AbonosRoutes } from "./abonos/routes";
import { ReportesRoutes } from "./reportes/routes";
import { AutorizacionRoutes } from "./autorizaciones/routes";
import { UnidadesMedidaRoutes } from "./unidades-medida/routes";
import { DevolucionesRoutes } from "./devoluciones/routes";
import { MermasRoutes } from "./mermas/routes";
import { CategoriasClientesRoutes } from "./categorias-clientes/routes";
import { CostosAdicionalesComprasRoutes } from "./costos-adicionales-compras/routes";
import { OrdenesCompraRoutes } from "./ordenes-compra/routes";
import { OrdenesCompraProductosRoutes } from "./ordenes-compra-productos/routes";
import { ImagenesProductosRoutes } from "./imagenes-productos/routes";
import { AuditoriaRoutes } from "./auditoria/routes";
import { EmpleadosRoutes } from "./empleados/routes";
import { DepartamentosEmpleadosRoutes } from "./departamentos-empleados/routes";
import { CargosEmpleadosRoutes } from "./cargos-empleados/routes";
import { HistorialSalariosRoutes } from "./historial-salarios/routes";
import { PeriodosPlanillaRoutes } from "./periodos-planilla/routes";
import { PlanillaDetalleRoutes } from "./planilla-detalle/routes";
import { PlanillaDeduccionesRoutes } from "./planilla-deducciones/routes";
import { PlanillaHorasExtraRoutes } from "./planilla-horas-extra/routes";
import { AnticiposSalarioRoutes } from "./anticipos-salario/routes";
import { PrestamosEmpleadosRoutes } from "./prestamos-empleados/routes";
import { CuotasPrestamosRoutes } from "./cuotas-prestamos/routes";
import { SolicitudesVacacionesRoutes } from "./solicitudes-vacaciones/routes";
import { AcumuladoVacacionesRoutes } from "./acumulado-vacaciones/routes";
import { AcumuladoDecimoPrimerMesRoutes } from "./acumulado-decimo-primer-mes/routes";
import { AcumuladoIndemnizacionRoutes } from "./acumulado-indemnizacion/routes";
import { LiquidacionesEmpleadosRoutes } from "./liquidaciones-empleados/routes";
import { PagosBeneficiosRoutes } from "./pagos-beneficios/routes";
import { RegistroAsistenciaRoutes } from "./registro-asistencia/routes";
import { ConfiguracionInssRoutes } from "./configuracion-inss/routes";
import { TablaTramoIrRoutes } from "./tabla-tramo-ir/routes";
import { FeriadosNacionalesRoutes } from "./feriados-nacionales/routes";

export class AppRoutes {

    static routes(gateway: AutorizacionGateway): Router {

        const router = Router();
        const authMiddleware = buildAuthMiddleware();

        router.use('/api/categoria-productos', [authMiddleware.validateJWT.bind(authMiddleware)], CategoriaProductoRoutes.routes);
        router.use('/api/proveedores', [authMiddleware.validateJWT.bind(authMiddleware)], ProveedoresRoutes.routes);
        router.use('/api/clientes', [authMiddleware.validateJWT.bind(authMiddleware)], ClientesRoutes.routes);
        router.use('/api/repartidores', [authMiddleware.validateJWT.bind(authMiddleware)], RepartidorRoutes.routes);
        router.use('/api/roles', [authMiddleware.validateJWT.bind(authMiddleware)], RolesRoutes.routes);
        router.use('/api/permisos', [authMiddleware.validateJWT.bind(authMiddleware)], PermisosRoutes.routes);
        router.use('/api/empresa', [authMiddleware.validateJWT.bind(authMiddleware)], EmpresasRoutes.routes);
        router.use('/api/pagos', [authMiddleware.validateJWT.bind(authMiddleware)], PagosRoutes.routes);
        router.use('/api/productos', [authMiddleware.validateJWT.bind(authMiddleware)], ProductosRoutes.routes);
        router.use('/api/auth', AuthRoutes.routes);
        router.use('/api/deliveries', [authMiddleware.validateJWT.bind(authMiddleware)], DeliveryRoutes.routes);
        router.use('/api/sesiones', [authMiddleware.validateJWT.bind(authMiddleware)], SesionesRoutes.routes);
        router.use('/api/ventas', [authMiddleware.validateJWT.bind(authMiddleware)], VentasRoutes.routes);
        router.use('/api/venta-delivery', [authMiddleware.validateJWT.bind(authMiddleware)], VentaDeliveryRoutes.routes);
        router.use('/api/venta-productos', [authMiddleware.validateJWT.bind(authMiddleware)], VentaProductoRoutes.routes);
        router.use('/api/venta-pagos', [authMiddleware.validateJWT.bind(authMiddleware)], VentaPagosRoutes.routes);
        router.use('/api/gastos', [authMiddleware.validateJWT.bind(authMiddleware)], GastosRoutes.routes);
        router.use('/api/pago-gastos', [authMiddleware.validateJWT.bind(authMiddleware)], PagoGastosRoutes.routes);
        router.use('/api/compras', [authMiddleware.validateJWT.bind(authMiddleware)], ComprasRoutes.routes);
        router.use('/api/compras-productos', [authMiddleware.validateJWT.bind(authMiddleware)], ComprasProductosRoutes.routes);
        router.use('/api/movimientos-inventario', [authMiddleware.validateJWT.bind(authMiddleware)], MovimientosInventarioRoutes.routes);
        router.use('/api/movimientos-compras', [authMiddleware.validateJWT.bind(authMiddleware)], MovimientosComprasRoutes.routes);
        router.use('/api/movimientos-ventas', [authMiddleware.validateJWT.bind(authMiddleware)], MovimientosVentasRoutes.routes);
        router.use('/api/cuentas-por-pagar', [authMiddleware.validateJWT.bind(authMiddleware)], CuentasPorPagarRoutes.routes);
        router.use('/api/pago-cuentas-por-pagar', [authMiddleware.validateJWT.bind(authMiddleware)], PagoCuentasPorPagarRoutes.routes);
        router.use('/api/cuentas-por-cobrar', [authMiddleware.validateJWT.bind(authMiddleware)], CuentasPorCobrarRoutes.routes);
        router.use('/api/abonos', [authMiddleware.validateJWT.bind(authMiddleware)], AbonosRoutes.routes);
        router.use('/api/reportes', [authMiddleware.validateJWT.bind(authMiddleware)], ReportesRoutes.routes);
        router.use('/api/autorizaciones', [authMiddleware.validateJWT.bind(authMiddleware)], AutorizacionRoutes.routes(gateway));
        router.use('/api/unidades-medida', [authMiddleware.validateJWT.bind(authMiddleware)], UnidadesMedidaRoutes.routes);
        router.use('/api/devoluciones', [authMiddleware.validateJWT.bind(authMiddleware)], DevolucionesRoutes.routes);
        router.use('/api/mermas', [authMiddleware.validateJWT.bind(authMiddleware)], MermasRoutes.routes);
        router.use('/api/categorias-clientes', [authMiddleware.validateJWT.bind(authMiddleware)], CategoriasClientesRoutes.routes);
        router.use('/api/costos-adicionales-compras', [authMiddleware.validateJWT.bind(authMiddleware)], CostosAdicionalesComprasRoutes.routes);
        router.use('/api/ordenes-compra', [authMiddleware.validateJWT.bind(authMiddleware)], OrdenesCompraRoutes.routes);
        router.use('/api/ordenes-compra-productos', [authMiddleware.validateJWT.bind(authMiddleware)], OrdenesCompraProductosRoutes.routes);
        router.use('/api/imagenes-productos', [authMiddleware.validateJWT.bind(authMiddleware)], ImagenesProductosRoutes.routes);
        router.use('/api/auditoria', [authMiddleware.validateJWT.bind(authMiddleware)], AuditoriaRoutes.routes);
        router.use('/api/empleados', [authMiddleware.validateJWT.bind(authMiddleware)], EmpleadosRoutes.routes);
        router.use('/api/departamentos-empleados', [authMiddleware.validateJWT.bind(authMiddleware)], DepartamentosEmpleadosRoutes.routes);
        router.use('/api/cargos-empleados', [authMiddleware.validateJWT.bind(authMiddleware)], CargosEmpleadosRoutes.routes);
        router.use('/api/historial-salarios', [authMiddleware.validateJWT.bind(authMiddleware)], HistorialSalariosRoutes.routes);
        router.use('/api/periodos-planilla', [authMiddleware.validateJWT.bind(authMiddleware)], PeriodosPlanillaRoutes.routes);
        router.use('/api/planilla-detalle', [authMiddleware.validateJWT.bind(authMiddleware)], PlanillaDetalleRoutes.routes);
        router.use('/api/planilla-deducciones', [authMiddleware.validateJWT.bind(authMiddleware)], PlanillaDeduccionesRoutes.routes);
        router.use('/api/planilla-horas-extra', [authMiddleware.validateJWT.bind(authMiddleware)], PlanillaHorasExtraRoutes.routes);
        router.use('/api/anticipos-salario', [authMiddleware.validateJWT.bind(authMiddleware)], AnticiposSalarioRoutes.routes);
        router.use('/api/prestamos-empleados', [authMiddleware.validateJWT.bind(authMiddleware)], PrestamosEmpleadosRoutes.routes);
        router.use('/api/cuotas-prestamos', [authMiddleware.validateJWT.bind(authMiddleware)], CuotasPrestamosRoutes.routes);
        router.use('/api/solicitudes-vacaciones', [authMiddleware.validateJWT.bind(authMiddleware)], SolicitudesVacacionesRoutes.routes);
        router.use('/api/acumulado-vacaciones', [authMiddleware.validateJWT.bind(authMiddleware)], AcumuladoVacacionesRoutes.routes);
        router.use('/api/acumulado-decimo-primer-mes', [authMiddleware.validateJWT.bind(authMiddleware)], AcumuladoDecimoPrimerMesRoutes.routes);
        router.use('/api/acumulado-indemnizacion', [authMiddleware.validateJWT.bind(authMiddleware)], AcumuladoIndemnizacionRoutes.routes);
        router.use('/api/liquidaciones-empleados', [authMiddleware.validateJWT.bind(authMiddleware)], LiquidacionesEmpleadosRoutes.routes);
        router.use('/api/pagos-beneficios', [authMiddleware.validateJWT.bind(authMiddleware)], PagosBeneficiosRoutes.routes);
        router.use('/api/registro-asistencia', [authMiddleware.validateJWT.bind(authMiddleware)], RegistroAsistenciaRoutes.routes);
        router.use('/api/configuracion-inss', [authMiddleware.validateJWT.bind(authMiddleware)], ConfiguracionInssRoutes.routes);
        router.use('/api/tabla-tramo-ir', [authMiddleware.validateJWT.bind(authMiddleware)], TablaTramoIrRoutes.routes);
        router.use('/api/feriados-nacionales', [authMiddleware.validateJWT.bind(authMiddleware)], FeriadosNacionalesRoutes.routes);

        return router;
    }

}